### ISSUE TITLE
Accordion not expanding on click

### ISSUE THREAD

**Issue by mapkbalaji** [Lunrtick/vue-bulma-accordion#10]
Hi,

I'm facing trouble in expanding the accordion on click. If I click on the accordion, no action takes place. It's working perfectly in my other component. Just not working in this component.

Here is the codepen of accordion not expanding:
[https://codepen.io/mapkbalaji/pen/GePpOQ](https://codepen.io/mapkbalaji/pen/GePpOQ)

Here is the codepen of accordion working:
[https://codepen.io/mapkbalaji/pen/EMGVLK](https://codepen.io/mapkbalaji/pen/EMGVLK)

I don't know the difference between these two, as they are the same but one is working and the other doesn't.

Thanks.

**Comment by Lunrtick** [comment]
Hey, at a glance this seems quite strange! I will look into it.

Thanks for including codepens by the way.

**Comment by hableel** [comment]
The not working one has an empty Array initially, and the working one is already populated.
I think it has to do with piece of code inside `mounted()` in `BulmaAccordion.vue`

`this.$nextTick(() => {
            this.$children.forEach((child, idx) => {
                const id = String(idx);
                child.setUniqueId(id);
                this.children_toggle_status[id] = false;
});`

Instead of looping through children in the parent, it can be done inside the child (`BulmaAccordionItem.vue`) `mounted()` without looping, and  also add `beforeDestroy()` code to cleanup.

This way it will work at all times even if you populate items later.

**Comment by Lunrtick** [comment]
The issue should be fixed now - sorry, had a busy few weeks there.
